name: Linter checks

on:
  pull_request:
  push:
    branches: 
      - "main"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  schedule:  # This is a weekly schedule, running only on the "main" branch every Sunday at midnight
    - cron: '0 0 * * 0'

# Make sure that there is one job per branch
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file  # Use .clang-format config file
          tidy-checks: ''  # Use .clang-tidy config file
          files-changed-only: false
          thread-comments: false

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: |
          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
          exit 1
